### ISSUE TITLE
Processing Problem near Innsbruck

### ISSUE THREAD

**Issue by manfredbrandl** [thomaskonrad/osm-austria-building-coverage#3]
There is a very big green area:
![img_1352](https://user-images.githubusercontent.com/5360273/36343327-1de47fa2-140b-11e8-8934-f7b29bc5886b.PNG)

**Comment by thomaskonrad** [comment]
Hi Manfred,

it seems to be gone now: https://osm-austria-building-coverage.thomaskonrad.at/map/?boundary_id=70101#12/47.2862/11.3789

Seems like somebody marked a whole region with `building=yes`.

Thanks for the feedback, closing this now.
Thomas
